# Generated by Django 2.0.3 on 2018-06-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descritipon',
            field=models.TextField(default='I like pizza', max_length=250),
            preserve_default=False,
        ),
    ]
