# Generated by Django 2.0.3 on 2018-06-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_descritipon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='descritipon',
            new_name='description',
        ),
    ]
